name: Thimar_amit
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  animate_do: ^3.3.3
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  kiwi: ^5.0.0
  get_it: ^7.6.7
  google_maps_flutter: ^2.5.3
  geocoding: ^2.1.1
  geolocator: ^11.0.0
  easy_localization: ^3.0.4
  image_picker: ^1.0.7
  shimmer: ^3.0.0
  lottie: ^3.1.0
  refresh_me: ^1.0.0
  pin_code_fields: ^8.0.1
  dio: ^5.4.1
  flutter_local_notifications: ^16.3.2
  firebase_messaging: ^14.7.17
  firebase_core: ^2.25.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/
    - assets/translations/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal.ttf

